"use client";
import { type FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export function BudgetSettings({ repositorySlug, monthlyBudgetUsd, canManageBudget }: { repositorySlug: string; monthlyBudgetUsd?: number; canManageBudget: boolean }) {
  const router = useRouter(); const [value, setValue] = useState(monthlyBudgetUsd?.toFixed(2) ?? ""); const [state, setState] = useState<"idle" | "saving" | "clearing" | "saved" | "error">("idle"); const [message, setMessage] = useState<string>(); const endpoint = `/api/app/repositories/${repositorySlug}/budget`;
  if (!canManageBudget) return <small className="budget-permission-note">A repository admin can set this monthly budget.</small>;
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState("saving"); setMessage(undefined); const response = await fetch(endpoint, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ monthlyBudgetUsd: value }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setState("error"); setMessage(payload.error ?? "Governor could not save that budget."); return; } setState("saved"); setMessage("Monthly budget saved."); router.refresh(); }
  async function clear() { setState("clearing"); setMessage(undefined); const response = await fetch(endpoint, { method: "DELETE" }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setState("error"); setMessage(payload.error ?? "Governor could not clear that budget."); return; } setValue(""); setState("saved"); setMessage("Monthly budget cleared."); router.refresh(); }
  return <form className="budget-settings" onSubmit={save}><label htmlFor={`budget-${repositorySlug.replace("/", "-")}`}>Monthly budget (USD)</label><div className="budget-settings-controls"><input id={`budget-${repositorySlug.replace("/", "-")}`} inputMode="decimal" type="number" min="0.01" max="1000000" step="0.01" value={value} onChange={(event) => setValue(event.target.value)} placeholder="100.00" required disabled={state === "saving" || state === "clearing"}/><button className="button small-button" type="submit" disabled={state === "saving" || state === "clearing"}>{state === "saving" ? "Saving…" : "Save budget"}</button>{monthlyBudgetUsd !== undefined && <button className="text-button budget-clear" type="button" onClick={clear} disabled={state === "saving" || state === "clearing"}>{state === "clearing" ? "Clearing…" : "Clear"}</button>}</div>{message && <small className={state === "error" ? "budget-message error" : "budget-message"} role={state === "error" ? "alert" : "status"}>{message}</small>}</form>;
}
