import Link from "next/link";
import type { Dashboard, Receipt, Repository, RepositoryOverview } from "@/lib/types";
import { observationFallback } from "@/lib/observations";
import { AutoRefresh } from "./live-refresh";

const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2}).format(value);
const compact=(value:number)=>new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(value);
const date=(value?:string)=>value?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value)):"No activity yet";
const confidence=(value:number)=>value>=.95?"Exact context":"Inferred context";

export function AppShell({children,active,login,repositories}:{children:React.ReactNode;active:"overview"|"setup"|"settings"|"repository";login:string;repositories:Repository[]}) { return <div className="app-shell"><aside className="sidebar"><Link className="wordmark" href="/app">governor<span>.</span></Link><div className="workspace-label">WORKSPACE</div><nav className="side-nav"><Nav href="/app" label="Overview" active={active==="overview"}/><Nav href="/app/setup" label="Setup" active={active==="setup"}/><Nav href="/app/settings" label="Settings" active={active==="settings"}/></nav><div className="repo-rail"><div className="workspace-label">REPOSITORIES</div>{repositories.length?repositories.map((repo)=><Link key={repo.id} className={active==="repository"?"repo-link selected":"repo-link"} href={`/app/repos/${repo.slug}`}><span className="repo-mark">⌘</span>{repo.slug}</Link>):<Link className="repo-link" href="/app/setup">Connect a repository</Link>}</div><div className="sidebar-footer"><span className="privacy-dot"/> Prompt-safe telemetry<br/><strong>@{login}</strong></div></aside><div className="mobile-bar"><Link className="wordmark" href="/app">governor<span>.</span></Link><Link href="/app/setup">Setup</Link></div><main className="app-main">{children}</main></div>; }
function Nav({href,label,active}:{href:string;label:string;active:boolean}) { return <Link href={href} className={active?"nav-item active":"nav-item"}><span>{label==="Overview"?"◫":label==="Setup"?"◎":"⚙"}</span>{label}</Link>; }

export function PageHeader({eyebrow,title,description,action}:{eyebrow:string;title:string;description?:string;action?:React.ReactNode}) { return <header className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</header>; }
export function MetricCard({label,value,detail,tone}:{label:string;value:string;detail?:string;tone?:"good"|"accent"}) { return <article className={`metric-card ${tone??""}`}><div className="metric-label">{label}</div><strong>{value}</strong>{detail&&<small>{detail}</small>}</article>; }

export function DemoDashboard({dashboard}:{dashboard:Dashboard}) { return <main className="demo-main"><PageHeader eyebrow="Governor public sandbox" title="AI spend, attached to engineering work." description={`Repository ${dashboard.repo.slug} · Aggregate demonstration data · Dollar amounts are transparent token-rate estimates.`}/><PrivacyNotice/><section className="metrics-grid"><MetricCard label="7-day estimated spend" value={money(dashboard.metrics.spend7d)}/><MetricCard label="30-day estimated spend" value={money(dashboard.metrics.spend30d)}/><MetricCard label="PRs with receipts" value={String(dashboard.metrics.prCount)}/><MetricCard label="Average attribution" value={`${Math.round(dashboard.metrics.avgConfidence*100)}%`} tone="good"/></section><ReceiptTable receipts={dashboard.receipts} repository={dashboard.repo} publicView/><section className="panel how-panel"><div><div className="eyebrow">How it works</div><h2>Evidence, not surveillance.</h2></div><p>Governor joins opt-in Codex token metadata to signed Git context, calculates with effective-dated rates, and posts the resulting estimate back to GitHub.</p></section></main>; }

export function Portfolio({items}:{items:RepositoryOverview[]}) { const spend7=items.reduce((sum,item)=>sum+item.metrics.spend7d,0); const spend30=items.reduce((sum,item)=>sum+item.metrics.spend30d,0); const receipts=items.flatMap((item)=>item.receipts.map((receipt)=>({...receipt,repo:item.repo}))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)); return <><PageHeader eyebrow="Engineering spend control" title="Your AI engineering workspace" description="Live, repository-level token-rate estimates with signed Git context." action={<AutoRefresh/>}/><section className="metrics-grid"><MetricCard label="7-day estimated spend" value={money(spend7)} detail="Across connected repositories"/><MetricCard label="30-day estimated spend" value={money(spend30)}/><MetricCard label="Active repositories" value={String(items.length)}/><MetricCard label="Receipts posted" value={String(receipts.length)} tone="good"/></section>{!items.length?<EmptyState/>:<section className="two-column"><div className="panel"><div className="panel-heading"><div><div className="eyebrow">Recent pull requests</div><h2>Receipts that changed the work</h2></div></div><div className="portfolio-list">{receipts.slice(0,6).map((item)=><Link className="portfolio-row" key={`${item.repo.id}-${item.prNumber}`} href={`/app/repos/${item.repo.slug}/pulls/${item.prNumber}`}><div><strong>{item.repo.slug} <span>#{item.prNumber}</span></strong><small>{item.title}</small></div><div><strong>{money(item.totalCost)}</strong><small>{item.eventCount} events · {confidence(item.confidence)}</small></div></Link>)}</div></div><div className="panel attention"><div className="eyebrow">Integration health</div><h2>{items.every((item)=>item.telemetryHealthy)?"Telemetry is flowing":"A repository needs its first turn"}</h2><p>{items.every((item)=>item.telemetryHealthy)?"Governor has recent attributed activity from every connected repository.":"Complete one Codex request from the repository to begin producing receipts."}</p><Link className="text-button" href="/app/setup">View setup status →</Link></div></section>}</>; }

export function RepositoryDashboard({overview}:{overview:RepositoryOverview}) { return <><PageHeader eyebrow="Repository overview" title={overview.repo.slug} description={`Default branch: ${overview.repo.defaultBranch} · Last activity: ${date(overview.lastActivityAt)}`} action={<AutoRefresh/>}/><section className="metrics-grid"><MetricCard label="7-day estimate" value={money(overview.metrics.spend7d)}/><MetricCard label="30-day estimate" value={money(overview.metrics.spend30d)}/><MetricCard label="PR receipts" value={String(overview.metrics.prCount)}/><MetricCard label="Attribution confidence" value={`${Math.round(overview.metrics.avgConfidence*100)}%`} tone="good"/></section><section className="two-column dashboard-top"><SpendTrend points={overview.spendTrend}/><ModelMix models={overview.modelSpend}/></section><section className="two-column"><ReceiptTable receipts={overview.receipts} repository={overview.repo}/><ActivityFeed events={overview.recentEvents}/></section></>; }
function SpendTrend({points}:{points:RepositoryOverview["spendTrend"]}) { const max=Math.max(...points.map((point)=>point.costUsd),.01); return <section className="panel"><div className="panel-heading"><div><div className="eyebrow">Last 14 days</div><h2>Estimated spend trend</h2></div><span className="muted">Token-rate estimate</span></div>{points.length?<div className="bar-chart">{points.map((point)=><div className="bar-item" key={point.date}><div className="bar-value">{money(point.costUsd)}</div><div className="bar" style={{height:`${Math.max(8,point.costUsd/max*150)}px`}}/><small>{point.date.slice(5)}</small></div>)}</div>:<ChartEmpty label="Spend will appear after the first attributed turn."/>}</section>; }
function ModelMix({models}:{models:RepositoryOverview["modelSpend"]}) { const total=models.reduce((sum,model)=>sum+model.costUsd,0); return <section className="panel"><div className="panel-heading"><div><div className="eyebrow">Model mix</div><h2>Where spend is concentrated</h2></div></div>{models.length?<div className="model-list">{models.map((model)=><div key={model.model} className="model-row"><div><strong>{model.model}</strong><small>{compact(model.inputTokens)} input · {compact(model.outputTokens)} output</small></div><div><strong>{money(model.costUsd)}</strong><span className="model-track"><i style={{width:`${total?model.costUsd/total*100:0}%`}}/></span></div></div>)}</div>:<ChartEmpty label="Model mix will appear after telemetry arrives."/>}</section>; }
function ChartEmpty({label}:{label:string}) { return <div className="chart-empty">{label}</div>; }
function ActivityFeed({events}:{events:RepositoryOverview["recentEvents"]}) { return <section className="panel"><div className="panel-heading"><div><div className="eyebrow">Recent activity</div><h2>Telemetry joined to work</h2></div></div>{events.length?<div className="activity-list">{events.slice(0,7).map((event)=><div className="activity-row" key={event.id}><span className="activity-pulse"/><div><strong>{event.model} usage attributed</strong><small>{event.branch ?? "No branch"} · {date(event.occurredAt)}</small></div><strong>{money(event.costUsd)}</strong></div>)}</div>:<ChartEmpty label="Waiting for the first attributed event."/>}</section>; }

export function ReceiptTable({receipts,repository,publicView}:{receipts:Receipt[];repository:Repository;publicView?:boolean}) { return <section className="panel receipts-panel"><div className="panel-heading"><div><div className="eyebrow">Pull request receipts</div><h2>Cost, with evidence</h2></div></div>{receipts.length?<div className="receipt-table">{receipts.map((receipt)=><Link key={receipt.prNumber} href={publicView?"/api/prs/"+receipt.prNumber+"/receipt?repo="+encodeURIComponent(repository.slug):`/app/repos/${repository.slug}/pulls/${receipt.prNumber}`} className="receipt-row"><div><strong>#{receipt.prNumber} · {receipt.title}</strong><small>{receipt.models.map((model)=>model.model).join(" · ")}</small></div><div><strong>{money(receipt.totalCost)}</strong><small>{receipt.eventCount} events · {confidence(receipt.confidence)}</small></div><span>→</span></Link>)}</div>:<ChartEmpty label="No pull request receipts have been created yet."/>}</section>; }

export function ReceiptDetail({receipt,repository}:{receipt:Receipt;repository:Repository}) { const observation=receipt.observation; const fallback=observationFallback(); return <><PageHeader eyebrow={`Pull request receipt · ${repository.slug}`} title={`#${receipt.prNumber} · ${receipt.title}`} description={`Updated ${date(receipt.updatedAt)} · Commit ${receipt.headSha.slice(0,7)}`} action={<a className="button small-button" href={`https://github.com/${repository.slug}/pull/${receipt.prNumber}`} target="_blank">Open GitHub ↗</a>}/><section className="receipt-hero"><div><span className="metric-label">Estimated Codex cost</span><strong>{money(receipt.totalCost)}</strong><small>{receipt.eventCount} usage events · {confidence(receipt.confidence)}</small></div><div className="confidence-card"><span className="privacy-dot"/><strong>{Math.round(receipt.confidence*100)}% confidence</strong><small>Signed Git context attribution</small></div></section><ObservationCard observation={observation}/><section className="two-column"><section className="panel"><div className="panel-heading"><div><div className="eyebrow">Cost breakdown</div><h2>Models and token counts</h2></div></div><div className="breakdown-list">{receipt.models.map((model)=><div className="breakdown-row" key={model.model}><div><strong>{model.model}</strong><small>{model.inputTokens.toLocaleString()} input · {model.cachedInputTokens.toLocaleString()} cached · {model.outputTokens.toLocaleString()} output</small></div><strong>{money(model.costUsd)}</strong></div>)}</div></section><section className="panel"><div className="eyebrow">Calculation</div><h2>Deterministic by design</h2><p>{receipt.explanation ?? "Governor calculated this token-rate estimate from recorded model token metadata and the effective rate at the time of use."}</p><dl className="calculation-list"><div><dt>Attribution</dt><dd>{confidence(receipt.confidence)}</dd></div><div><dt>Rate method</dt><dd>Effective-dated token rates</dd></div><div><dt>Privacy</dt><dd>No prompts or code stored</dd></div></dl></section></section><PrivacyNotice/></>; }
function ObservationCard({observation}:{observation?:Receipt["observation"]}) { const fallback=observationFallback(); return <section className="observation-card"><div className="observation-icon">✦</div><div><div className="eyebrow">Governor observation</div><h2>{observation?.title ?? fallback.title}</h2><p>{observation?.explanation ?? fallback.body}</p>{observation&&<><div className="observation-evidence">{observation.evidence}</div><div className="observation-meta">{observation.impactUsd!==undefined&&<span>Estimated impact · {money(observation.impactUsd)}</span>}<span>Confidence · {Math.round(observation.confidence*100)}%</span><span>Deterministic calculation v{observation.calculationVersion.replace("v","")}</span></div></>}</div></section>; }
export function PrivacyNotice() { return <div className="privacy-notice"><span className="privacy-dot"/><span><strong>Prompt-safe by design.</strong> Governor stores token metadata and Git context—never prompts, responses, or generated code.</span></div>; }
export function EmptyState() { return <section className="empty-state"><div className="empty-icon">⌘</div><div><div className="eyebrow">No repositories yet</div><h2>Connect your first repository</h2><p>Install the Governor GitHub App, run the one-time Codex command, and complete a real turn to begin receiving receipts.</p><Link className="button" href="/app/setup">Complete setup →</Link></div></section>; }
