CREATE TABLE IF NOT EXISTS repositories (id TEXT PRIMARY KEY, slug TEXT UNIQUE NOT NULL, installation_id BIGINT, default_branch TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS developers (id TEXT PRIMARY KEY, github_login TEXT NOT NULL, email TEXT, token_hash TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS model_rates (model TEXT NOT NULL, effective_from DATE NOT NULL, input_per_mtok NUMERIC NOT NULL, output_per_mtok NUMERIC NOT NULL, cached_input_per_mtok NUMERIC NOT NULL, PRIMARY KEY(model, effective_from));
CREATE TABLE IF NOT EXISTS session_contexts (session_id TEXT PRIMARY KEY, repository_slug TEXT NOT NULL, branch TEXT NOT NULL, head_sha TEXT NOT NULL, developer_id TEXT NOT NULL, observed_at TIMESTAMPTZ NOT NULL);
CREATE INDEX IF NOT EXISTS session_contexts_developer_observed ON session_contexts(developer_id, observed_at DESC);
CREATE TABLE IF NOT EXISTS usage_events (id TEXT PRIMARY KEY, event_key TEXT UNIQUE NOT NULL, source TEXT NOT NULL, session_id TEXT, repository_id TEXT REFERENCES repositories(id), developer_id TEXT REFERENCES developers(id), branch TEXT, head_sha TEXT, model TEXT NOT NULL, input_tokens BIGINT NOT NULL, output_tokens BIGINT NOT NULL, cached_input_tokens BIGINT NOT NULL, occurred_at TIMESTAMPTZ NOT NULL, cost_usd NUMERIC NOT NULL, rate_effective_from DATE NOT NULL, attribution_method TEXT NOT NULL, attribution_confidence REAL NOT NULL);
CREATE INDEX IF NOT EXISTS usage_events_repo_branch_time ON usage_events(repository_id, branch, occurred_at);
CREATE TABLE IF NOT EXISTS pull_requests (repository_id TEXT REFERENCES repositories(id), number INTEGER NOT NULL, branch TEXT NOT NULL, head_sha TEXT NOT NULL, title TEXT NOT NULL, state TEXT NOT NULL, comment_id BIGINT, updated_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(repository_id, number));
CREATE TABLE IF NOT EXISTS receipts (repository_id TEXT REFERENCES repositories(id), pr_number INTEGER NOT NULL, receipt JSONB NOT NULL, PRIMARY KEY(repository_id, pr_number));
